version: '3.8'

services:
  db:
    image: postgres:15
    container_name: plantas_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: plantasBD
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql

  backend:
    build: ./backend
    container_name: plantas_backend
    ports:
      - "3000:3000"
    environment:
      DB_USER: postgres
      DB_HOST: db
      DB_NAME: plantasBD
      DB_PASSWORD: password
      DB_PORT: 5432
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: plantas_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
